<?php

/********************************************************************************
 * This file was automatically generated by the version-loader-generator script
 * whenever the composer update command is run.
 *
 * WARNING: Do not modify this file directly. Your changes will be overwritten.
 *******************************************************************************/

use PublishPress\StripePhp\VersionLoader;

class VersionLoaderCest
{
    public function testAllVersionsAreRegistered(IntegrationTester $I)
    {
        $loader = VersionLoader::getInstance();

        $registeredVersions = $loader->getVersions();

        $I->assertNotEmpty($registeredVersions);
        $I->assertEquals([
            '2.0.0.1' => 'PublishPress\StripePhp\initialize2Dot0Dot0Dot1',
            '2.0.0.2' => 'PublishPress\StripePhp\initialize2Dot0Dot0Dot2',
            '20.3.1.2' => 'PublishPress\StripePhp\initialize20Dot3Dot1Dot2',
        ], $registeredVersions);
    }

    public function testLatestVersionIsTheCurrentVersion(IntegrationTester $I)
    {
        $loader = VersionLoader::getInstance();

        $latestVersion = $loader->latestVersion();

        $I->assertEquals('20.3.1.2', $latestVersion);
    }

    public function testLatestVersionCallbackIsTheLastOne(IntegrationTester $I)
    {
        $loader = VersionLoader::getInstance();

        $latestVersionCallback = $loader->latestVersionCallback();

        $I->assertEquals('PublishPress\StripePhp\initialize20Dot3Dot1Dot2', $latestVersionCallback);
    }

    public function testInitializeLatestVersion(IntegrationTester $I)
    {
        $loader = VersionLoader::getInstance();

        $loader->initializeLatestVersion();

        $I->assertTrue(class_exists('PublishPress\Stripe\StripeClient'));

        $didAction = (bool)did_action('publishpress_stripe_php_20Dot3Dot1Dot2_initialized');
        $I->assertTrue($didAction);
    }
}
